name: Sync to UIUC Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UIUC_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config user.name "bee0511"
          git config user.email "bee0511@gmail.com"

      - name: Add UIUC repo as upstream remote
        run: |
          git remote add upstream git@github.com:illinois-cs-coursework/sp25_cs438_jy98.git

      - name: Fetch UIUC repo (upstream)
        run: git fetch upstream

      - name: Merge upstream changes into local main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push merged changes to UIUC repo
        run: git push upstream main
